### PR TITLE
Binary writing/reading for administrator cache

### PR DESCRIPTION
**Pull request by CrazyHackGUT**
See #95 for details.
This PR proposals binary format for writing/reading administrators, groups and overrides.

### CODE REVIEW

**Comment by BlackYuzia** [comment]
Tested.
Groups are work.

**Comment by CrazyHackGUT** [comment]
Waiting tests from @BlackYuzia for next step.

**Comment by CrazyHackGUT** [comment]
@BlackYuzia, test admin writing/reading.

**Comment by BlackYuzia** [comment]
Tested. ~~Keys~~ Admins is working.

**Comment by CrazyHackGUT** [comment]
Now it's ready to merge.

**Pull request merged**
